#!/usr/bin/env bash
set -euo pipefail

# Regenerates supabase/seed_tricks.sql from prod via the public REST API.
# Trick catalog only (positions + approved tricks) - no user data, no DB password.
# Uses the anon/publishable key, which grants public read on positions and
# approved tricks (see supabase/schemas/rls_and_grants.sql).
#
# Usage:
#   scripts/refresh-seed.sh
#
# Overridable via env (defaults match lib/supabase_config.dart):
#   SUPABASE_URL, SUPABASE_ANON_KEY
#
# Commit the regenerated supabase/seed_tricks.sql so every dev gets it via `supabase db reset`.

SUPABASE_URL="${SUPABASE_URL:-https://ubsmdiesqofnfxuicwxj.supabase.co}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-sb_publishable_EHLEMf4zv4Im0u3O6cwhXA_WzIuNDT9}"

command -v jq >/dev/null || { echo "jq is required (brew install jq)"; exit 1; }

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/seed_tricks.sql"
JQ="$ROOT/scripts/json_to_seed.jq"
REST="$SUPABASE_URL/rest/v1"

fetch() {
  curl -fsS "$REST/$1" \
    -H "apikey: $SUPABASE_ANON_KEY" \
    -H "Authorization: Bearer $SUPABASE_ANON_KEY"
}

echo "Fetching trick catalog from $SUPABASE_URL ..."
POSITIONS="$(fetch 'positions?select=*&order=id')"
TRICKS="$(fetch 'tricks?select=*&status=eq.1&order=id')"

INSERTS="$(jq -n \
  --argjson positions "$POSITIONS" \
  --argjson tricks "$TRICKS" \
  '{positions: $positions, tricks: $tricks}' | jq -r -f "$JQ")"

{
  echo "-- Generated by scripts/refresh-seed.sh from prod REST API. Do not edit by hand."
  echo "-- Trick catalog only (positions + approved tricks); contains no user data."
  echo "-- Regenerate with: scripts/refresh-seed.sh"
  echo
  echo "$INSERTS"
  echo
  echo "-- Advance identity sequences past the inserted ids."
  echo "select setval(pg_get_serial_sequence('positions', 'id'), coalesce((select max(id) from positions), 1));"
  echo "select setval(pg_get_serial_sequence('tricks', 'id'), coalesce((select max(id) from tricks), 1));"
} > "$OUT"

echo "Wrote $OUT ($(jq 'length' <<<"$TRICKS") tricks, $(jq 'length' <<<"$POSITIONS") positions)."
